### ISSUE TITLE
Analytics on multiple sites with single Fathom instance

### ISSUE THREAD

**Issue by edjw** [usefathom/fathom#118] opened 2018-08-31 18:14 UTC
At the moment if I put the tracking snippet on multiple websites, all the data is amalgamated together. It would be great if there could be differentiation between analytics data from different websites within Fathom.

Has anyone got any good workaround for this at the moment? I'd rather not have multiple versions of Fathom running on my server at the same time!

**Comment by dannyvankooten** [comment] 2018-09-01 08:30
Duplicate of #50, we'll start the work on this very soon (within the next few weeks, most likely).

For now the way to go about this is to spin up multiple Fathom instances. Can you elaborate why you'd rather not do this?

**Comment by edjw** [comment] 2018-09-01 08:48
Sorry about that. I did look I promise! :-)

To be honest it's just about simplicity. Setting up one instance of Fathom was the first time I ever successfully self-hosted something. (Thanks to your docs.) I could set up multiple instances but not sure if there are things that are complicated when you have multiple on the same server. Port numbers for example? Some documentation on what if anything happens when you run multiple instances would be good.

**Comment by dannyvankooten** [comment] 2018-09-01 09:01
Gotcha @edjw. We'll work on both of those things then!

- Improving the documentation for running Fathom multiple times on the  same server (basically it's a duplication of the [installation instructions](https://github.com/usefathom/fathom/wiki/Installing-&-running-Fathom), but with a different port number in the configuration file & accompanying nginx server block).
- Allowing you to track multiple sites with just a single Fathom instance.

I'm closing this issue to keep our list of issues manageable, but please know that that doesn't mean we're not going to act on this. Cheers!

**Closed by dannyvankooten** 2018-09-01 09:01 UTC

**Comment by edjw** [comment] 2018-09-01 10:15
Brilliant. I think both options have good use cases

**Comment by joshuadegier** [comment] 2019-04-03 10:30
Thanks for the explanation @dannyvankooten, exactly what I was searching for. Is there any safe range for the port numbers (e.g. 90000 - 90100 f.e.)?
