### ISSUE TITLE
multiple site support

### ISSUE THREAD

**Issue by zhy1stgg** [usefathom/fathom#53] opened 2018-06-08 09:53 UTC
suggestion:

How about add support for multiple site (domain), so I can select to see  which site's data.

And in backend,  filter by hostname in pageviews table.

same as #36

**Comment by dannyvankooten** [comment] 2018-06-08 11:23
Duplicate of #50, closing this one to keep discussion in a central place.

**Closed by dannyvankooten** 2018-06-08 11:23 UTC
