### ISSUE TITLE
How to tackle referrer spam?

### ISSUE THREAD

**Issue by Spone** [usefathom/fathom#170] opened 2018-10-23 07:34 UTC
Hi there,

I've been running my own Fathom instance for a few days to track several low-traffic websites, but I already get spam in my referrers:

![image](https://user-images.githubusercontent.com/38524/47343281-0dd86200-d6a6-11e8-9420-3ab5fd2822b4.png)

![image](https://user-images.githubusercontent.com/38524/47343304-192b8d80-d6a6-11e8-9538-9ea9e432c63b.png)

Any idea on how Fathom could filter that out? Maybe use some kind of [existing blacklist](https://github.com/matomo-org/referrer-spam-blacklist/blob/master/spammers.txt)?

**Comment by mgibbs189** [comment] 2018-10-31 19:46
Duplicate of #154 😄

**Closed** 2018-11-09 09:38 UTC
Labels: enhancement
