### ISSUE TITLE
Pages not appearing correctly

### ISSUE THREAD

**Issue by 0urobor0s** [usefathom/fathom#101] opened 2018-07-25 12:03 UTC
Deployed the project with docker and setup the tracking in a wordpress instanse in a different domain and a different server.
This is tracking page visits correctly, since I have other tracker to compare to, but all pages appear with ``/undefinedfunction search() { [native code] }`` instead of the page visited.

**Comment by dannyvankooten** [comment] 2018-07-26 07:12
Hi @0urobor0s,

If you inspect the Network requests for the site that is being tracked, what do the requests to `your-fathom-url.com/collect` look like? Does it show the correct page URL's there?

**Comment by 0urobor0s** [comment] 2018-07-26 13:48
At first thought that the requests were going to be ``POST`` but then realized that they were ``GET``, this was a pleasant surprise.
The requests are only being made once, when I first enter the site with a clean browser history (private nagivation) and they contain the id and the above but encoded
``GET /collect?id=ANON&pid=ANON&p=undefinedfunction%20search()%20%7B%20%5Bnative%20code%5D%20%7D&h=undefined%2F%2Fundefined&r=&u=0&nv=0&ns=0 HTTP/1.1\" 200 42``

**Comment by dannyvankooten** [comment] 2018-07-26 18:56
Hey @0urobor0s,

Thanks, that helps! I've never come across this before, but at least now we know that this error is happening on the client and that the server is accepting it despite it being mumbo jumbo (since you do have stats showing up, right?).

Is this on a live site by any chance, and could I take a look at the site directly? Because this isn't just happening for you but all your site visitors, right (so we can rule out it being an issue with your specific browser or combination of browser add-ons)? 

If you'd rather not share the site here then you can email me directly at hi@dvk.co.

Thanks in advance!

**Comment by dannyvankooten** [comment] 2018-07-27 07:07
Bug confirmed, introduced by c6ec64a2678e09612c29189c0aff9590755aa650. Seems we can't just use the canonical element like that after all.

**Comment by dannyvankooten** [comment] 2018-07-27 07:09
Fixed in 98c5487a5800978f2c118fb2fa1dc71659163c01

**Closed by dannyvankooten** 2018-07-27 07:09 UTC
Labels: bug
